//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public string ID_Cuenta { get; set; }
        public string Cuit_Cuil { get; set; }
        public string ID_Tipo_Cuenta { get; set; }
        public string ID_movimiento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Tipo_Cuenta Tipo_Cuenta { get; set; }
        public virtual Movimiento Movimiento { get; set; }
    }
}
