//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public string ID_movimiento { get; set; }
        public string ID_tipo_Movimiento { get; set; }
        public string Descripción { get; set; }
        public Nullable<System.DateTime> Fecha_Hora { get; set; }
        public string Monto { get; set; }
        public string ID_cuenta_origen { get; set; }
        public string ID_cuenta_final { get; set; }
    
        public virtual Movimiento Movimientos1 { get; set; }
        public virtual Movimiento Movimiento1 { get; set; }
        public virtual Tipo_Movimientos Tipo_Movimientos { get; set; }
    }
}
